#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:10:36 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import welcomelibrary1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = library_portal (root)
    welcomelibrary1_support.init(root, top)
    root.mainloop()

w = None
def create_library_portal(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = library_portal (w)
    welcomelibrary1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_library_portal():
    global w
    w.destroy()
    w = None


class library_portal:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"
        font9 = "-family {Segoe UI} -size 11 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x338+738+213")
        top.title("library portal")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.1, rely=0.15, height=61, width=467)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''WELOCME TO COLLEGE LIBRARY''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.37, rely=0.38, height=36, width=154)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''LOGIN PORTAL''')

        self.eloginbutton = Button(top)
        self.eloginbutton.place(relx=0.2, rely=0.68, height=42, width=100)
        self.eloginbutton.configure(activebackground="#d9d9d9")
        self.eloginbutton.configure(activeforeground="#000000")
        self.eloginbutton.configure(background="#d9d9d9")
        self.eloginbutton.configure(command=welcomelibrary1_support.employeefunction)
        self.eloginbutton.configure(disabledforeground="#a3a3a3")
        self.eloginbutton.configure(foreground="#000000")
        self.eloginbutton.configure(highlightbackground="#d9d9d9")
        self.eloginbutton.configure(highlightcolor="black")
        self.eloginbutton.configure(pady="0")
        self.eloginbutton.configure(text='''EMPLOYEE''')

        self.sloginbutton = Button(top)
        self.sloginbutton.place(relx=0.63, rely=0.68, height=42, width=90)
        self.sloginbutton.configure(activebackground="#d9d9d9")
        self.sloginbutton.configure(activeforeground="#000000")
        self.sloginbutton.configure(background="#d9d9d9")
        self.sloginbutton.configure(command=welcomelibrary1_support.studentfunction)
        self.sloginbutton.configure(disabledforeground="#a3a3a3")
        self.sloginbutton.configure(foreground="#000000")
        self.sloginbutton.configure(highlightbackground="#d9d9d9")
        self.sloginbutton.configure(highlightcolor="black")
        self.sloginbutton.configure(pady="0")
        self.sloginbutton.configure(text='''STUDENT''')






if __name__ == '__main__':
    vp_start_gui()



