#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 08:17:03 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def addbookfunction():
    print('employeeoption3_support.addbookfunction')
    sys.stdout.flush()

def allbookfunction():
    print('employeeoption3_support.allbookfunction')
    sys.stdout.flush()

def delbookfunction():
    print('employeeoption3_support.delbookfunction')
    sys.stdout.flush()

def eneweregfunction():
    print('employeeoption3_support.eneweregfunction')
    sys.stdout.flush()

def issuedfunction():
    print('employeeoption3_support.issuedfunction')
    sys.stdout.flush()

def searchbookfunction():
    print('employeeoption3_support.searchbookfunction')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import employeeoption3
    employeeoption3.vp_start_gui()


