#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:13:57 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import searching8_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    searching8_support.set_Tk_var()
    top = Searching_Block (root)
    searching8_support.init(root, top)
    root.mainloop()

w = None
def create_Searching_Block(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    searching8_support.set_Tk_var()
    top = Searching_Block (w)
    searching8_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Searching_Block():
    global w
    w.destroy()
    w = None


class Searching_Block:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"

        top.geometry("551x303+671+150")
        top.title("Searching Block")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.07, rely=0.13, height=41, width=447)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''SEARCHING PORTAL''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.11, rely=0.46, height=34, width=76)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Subject''')

        self.esubjectentry = Entry(top)
        self.esubjectentry.place(relx=0.34, rely=0.46,height=26, relwidth=0.5)
        self.esubjectentry.configure(background="white")
        self.esubjectentry.configure(disabledforeground="#a3a3a3")
        self.esubjectentry.configure(font="TkFixedFont")
        self.esubjectentry.configure(foreground="#000000")
        self.esubjectentry.configure(highlightbackground="#d9d9d9")
        self.esubjectentry.configure(highlightcolor="black")
        self.esubjectentry.configure(insertbackground="black")
        self.esubjectentry.configure(selectbackground="#c4c4c4")
        self.esubjectentry.configure(selectforeground="black")
        self.esubjectentry.configure(textvariable=searching8_support.esub)

        self.esearchbutton = Button(top)
        self.esearchbutton.place(relx=0.11, rely=0.73, height=42, width=98)
        self.esearchbutton.configure(activebackground="#d9d9d9")
        self.esearchbutton.configure(activeforeground="#000000")
        self.esearchbutton.configure(background="#d9d9d9")
        self.esearchbutton.configure(command=searching8_support.esearchfunction)
        self.esearchbutton.configure(disabledforeground="#a3a3a3")
        self.esearchbutton.configure(foreground="#000000")
        self.esearchbutton.configure(highlightbackground="#d9d9d9")
        self.esearchbutton.configure(highlightcolor="black")
        self.esearchbutton.configure(pady="0")
        self.esearchbutton.configure(text='''Search''')

        self.eclearbutton = Button(top)
        self.eclearbutton.place(relx=0.4, rely=0.73, height=42, width=98)
        self.eclearbutton.configure(activebackground="#d9d9d9")
        self.eclearbutton.configure(activeforeground="#000000")
        self.eclearbutton.configure(background="#d9d9d9")
        self.eclearbutton.configure(command=searching8_support.eclearfunction)
        self.eclearbutton.configure(disabledforeground="#a3a3a3")
        self.eclearbutton.configure(foreground="#000000")
        self.eclearbutton.configure(highlightbackground="#d9d9d9")
        self.eclearbutton.configure(highlightcolor="black")
        self.eclearbutton.configure(pady="0")
        self.eclearbutton.configure(text='''Clear''')

        self.ebackbutton = Button(top)
        self.ebackbutton.place(relx=0.71, rely=0.73, height=42, width=98)
        self.ebackbutton.configure(activebackground="#d9d9d9")
        self.ebackbutton.configure(activeforeground="#000000")
        self.ebackbutton.configure(background="#d9d9d9")
        self.ebackbutton.configure(command=searching8_support.ebackfunction)
        self.ebackbutton.configure(disabledforeground="#a3a3a3")
        self.ebackbutton.configure(foreground="#000000")
        self.ebackbutton.configure(highlightbackground="#d9d9d9")
        self.ebackbutton.configure(highlightcolor="black")
        self.ebackbutton.configure(pady="0")
        self.ebackbutton.configure(text='''Back''')

        self.elogoutbutton = Button(top)
        self.elogoutbutton.place(relx=0.87, rely=0.0, height=42, width=78)
        self.elogoutbutton.configure(activebackground="#d9d9d9")
        self.elogoutbutton.configure(activeforeground="#000000")
        self.elogoutbutton.configure(background="#d9d9d9")
        self.elogoutbutton.configure(command=searching8_support.elogoutfunction)
        self.elogoutbutton.configure(disabledforeground="#a3a3a3")
        self.elogoutbutton.configure(foreground="#000000")
        self.elogoutbutton.configure(highlightbackground="#d9d9d9")
        self.elogoutbutton.configure(highlightcolor="black")
        self.elogoutbutton.configure(pady="0")
        self.elogoutbutton.configure(text='''logout''')






if __name__ == '__main__':
    vp_start_gui()



