#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 07:11:20 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import employeelogin2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    employeelogin2_support.set_Tk_var()
    top = Employee_Portal (root)
    employeelogin2_support.init(root, top)
    root.mainloop()

w = None
def create_Employee_Portal(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    employeelogin2_support.set_Tk_var()
    top = Employee_Portal (w)
    employeelogin2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Employee_Portal():
    global w
    w.destroy()
    w = None


class Employee_Portal:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"
        font9 = "-family {Segoe UI} -size 10 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("600x326+650+150")
        top.title("Employee Portal")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.17, rely=0.12, height=44, width=399)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''EMPLOYEE LOGIN PORTAL''')

        self.eloginbutton = Button(top)
        self.eloginbutton.place(relx=0.1, rely=0.77, height=42, width=128)
        self.eloginbutton.configure(activebackground="#d9d9d9")
        self.eloginbutton.configure(activeforeground="#000000")
        self.eloginbutton.configure(background="#d9d9d9")
        self.eloginbutton.configure(command=employeelogin2_support.eloginfunction)
        self.eloginbutton.configure(disabledforeground="#a3a3a3")
        self.eloginbutton.configure(foreground="#000000")
        self.eloginbutton.configure(highlightbackground="#d9d9d9")
        self.eloginbutton.configure(highlightcolor="black")
        self.eloginbutton.configure(pady="0")
        self.eloginbutton.configure(text='''Login''')

        self.eclearbutton = Button(top)
        self.eclearbutton.place(relx=0.4, rely=0.77, height=42, width=128)
        self.eclearbutton.configure(activebackground="#d9d9d9")
        self.eclearbutton.configure(activeforeground="#000000")
        self.eclearbutton.configure(background="#d9d9d9")
        self.eclearbutton.configure(command=employeelogin2_support.eclearfunction)
        self.eclearbutton.configure(disabledforeground="#a3a3a3")
        self.eclearbutton.configure(foreground="#000000")
        self.eclearbutton.configure(highlightbackground="#d9d9d9")
        self.eclearbutton.configure(highlightcolor="black")
        self.eclearbutton.configure(pady="0")
        self.eclearbutton.configure(text='''Clear''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.72, rely=0.77, height=42, width=128)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=employeelogin2_support.ebackfunction)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Back''')

        self.eidentry = Entry(top)
        self.eidentry.place(relx=0.33, rely=0.34,height=26, relwidth=0.44)
        self.eidentry.configure(background="white")
        self.eidentry.configure(disabledforeground="#a3a3a3")
        self.eidentry.configure(font="TkFixedFont")
        self.eidentry.configure(foreground="#000000")
        self.eidentry.configure(highlightbackground="#d9d9d9")
        self.eidentry.configure(highlightcolor="black")
        self.eidentry.configure(insertbackground="black")
        self.eidentry.configure(selectbackground="#c4c4c4")
        self.eidentry.configure(selectforeground="black")
        self.eidentry.configure(textvariable=employeelogin2_support.eid)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.12, rely=0.34, height=34, width=73)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Emp.ID''')

        self.epasswordentry = Entry(top)
        self.epasswordentry.place(relx=0.33, rely=0.52, height=26, relwidth=0.44)

        self.epasswordentry.configure(background="white")
        self.epasswordentry.configure(disabledforeground="#a3a3a3")
        self.epasswordentry.configure(font="TkFixedFont")
        self.epasswordentry.configure(foreground="#000000")
        self.epasswordentry.configure(highlightbackground="#d9d9d9")
        self.epasswordentry.configure(highlightcolor="black")
        self.epasswordentry.configure(insertbackground="black")
        self.epasswordentry.configure(selectbackground="#c4c4c4")
        self.epasswordentry.configure(selectforeground="black")
        self.epasswordentry.configure(textvariable=employeelogin2_support.epassword)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.1, rely=0.52, height=34, width=95)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Password''')






if __name__ == '__main__':
    vp_start_gui()



