#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:08:46 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import welcomestudent10_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Student_Portal (root)
    welcomestudent10_support.init(root, top)
    root.mainloop()

w = None
def create_Student_Portal(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Student_Portal (w)
    welcomestudent10_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Student_Portal():
    global w
    w.destroy()
    w = None


class Student_Portal:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"

        top.geometry("600x293+650+150")
        top.title("Student Portal")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.08, rely=0.14, height=31, width=507)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''WELCOME TO STUDENT PORTAL''')

        self.sregisterbutton = Button(top)
        self.sregisterbutton.place(relx=0.13, rely=0.55, height=42, width=188)
        self.sregisterbutton.configure(activebackground="#d9d9d9")
        self.sregisterbutton.configure(activeforeground="#000000")
        self.sregisterbutton.configure(background="#d9d9d9")
        self.sregisterbutton.configure(command=welcomestudent10_support.sregisterfunction)
        self.sregisterbutton.configure(disabledforeground="#a3a3a3")
        self.sregisterbutton.configure(foreground="#000000")
        self.sregisterbutton.configure(highlightbackground="#d9d9d9")
        self.sregisterbutton.configure(highlightcolor="black")
        self.sregisterbutton.configure(pady="0")
        self.sregisterbutton.configure(text='''Register''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.55, rely=0.55, height=42, width=218)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=welcomestudent10_support.sloginfunction)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Login''')






if __name__ == '__main__':
    vp_start_gui()



