#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 08:33:47 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global ssub
    ssub = StringVar()

def sbackfunction():
    print('searching14_support.sbackfunction')
    sys.stdout.flush()

def sclearfunction():
    print('searching14_support.sclearfunction')
    sys.stdout.flush()

def searchfunction():
    print('searching14_support.searchfunction')
    sys.stdout.flush()

def slogoutfunction():
    print('searching14_support.slogoutfunction')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import searching14
    searching14.vp_start_gui()


