#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:05:54 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global sroll
    sroll = StringVar()
    global spassword
    spassword = StringVar()

def backfunction():
    print('studentloginportal12_support.backfunction')
    sys.stdout.flush()

def clearfunction():
    print('studentloginportal12_support.clearfunction')
    sys.stdout.flush()

def loginfunction():
    print('studentloginportal12_support.loginfunction')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import studentloginportal12
    studentloginportal12.vp_start_gui()


