#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:05:59 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import studentloginportal12_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    studentloginportal12_support.set_Tk_var()
    top = Loging_Block (root)
    studentloginportal12_support.init(root, top)
    root.mainloop()

w = None
def create_Loging_Block(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    studentloginportal12_support.set_Tk_var()
    top = Loging_Block (w)
    studentloginportal12_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Loging_Block():
    global w
    w.destroy()
    w = None


class Loging_Block:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 10 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"

        top.geometry("758x429+641+150")
        top.title("Loging Block")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.05, rely=0.16, relheight=0.71, relwidth=0.89)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=673)

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.13, rely=0.2, height=34, width=85)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''RoLL No''')

        self.rollentry = Entry(self.Canvas1)
        self.rollentry.place(relx=0.36, rely=0.2,height=26, relwidth=0.5)
        self.rollentry.configure(background="white")
        self.rollentry.configure(disabledforeground="#a3a3a3")
        self.rollentry.configure(font="TkFixedFont")
        self.rollentry.configure(foreground="#000000")
        self.rollentry.configure(highlightbackground="#d9d9d9")
        self.rollentry.configure(highlightcolor="black")
        self.rollentry.configure(insertbackground="black")
        self.rollentry.configure(selectbackground="#c4c4c4")
        self.rollentry.configure(selectforeground="black")
        self.rollentry.configure(textvariable=studentloginportal12_support.sroll)

        self.Label3 = Label(self.Canvas1)
        self.Label3.place(relx=0.13, rely=0.4, height=34, width=95)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Password''')

        self.passwordentry = Entry(self.Canvas1)
        self.passwordentry.place(relx=0.36, rely=0.4,height=26, relwidth=0.5)
        self.passwordentry.configure(background="white")
        self.passwordentry.configure(disabledforeground="#a3a3a3")
        self.passwordentry.configure(font="TkFixedFont")
        self.passwordentry.configure(foreground="#000000")
        self.passwordentry.configure(highlightbackground="#d9d9d9")
        self.passwordentry.configure(highlightcolor="black")
        self.passwordentry.configure(insertbackground="black")
        self.passwordentry.configure(selectbackground="#c4c4c4")
        self.passwordentry.configure(selectforeground="black")
        self.passwordentry.configure(show="*")
        self.passwordentry.configure(textvariable=studentloginportal12_support.spassword)

        self.loginbutton = Button(self.Canvas1)
        self.loginbutton.place(relx=0.12, rely=0.73, height=42, width=128)
        self.loginbutton.configure(activebackground="#d9d9d9")
        self.loginbutton.configure(activeforeground="#000000")
        self.loginbutton.configure(background="#d9d9d9")
        self.loginbutton.configure(command=studentloginportal12_support.loginfunction)
        self.loginbutton.configure(disabledforeground="#a3a3a3")
        self.loginbutton.configure(foreground="#000000")
        self.loginbutton.configure(highlightbackground="#d9d9d9")
        self.loginbutton.configure(highlightcolor="black")
        self.loginbutton.configure(pady="0")
        self.loginbutton.configure(text='''Login''')

        self.clearbuttton = Button(self.Canvas1)
        self.clearbuttton.place(relx=0.42, rely=0.73, height=42, width=128)
        self.clearbuttton.configure(activebackground="#d9d9d9")
        self.clearbuttton.configure(activeforeground="#000000")
        self.clearbuttton.configure(background="#d9d9d9")
        self.clearbuttton.configure(command=studentloginportal12_support.clearfunction)
        self.clearbuttton.configure(disabledforeground="#a3a3a3")
        self.clearbuttton.configure(foreground="#000000")
        self.clearbuttton.configure(highlightbackground="#d9d9d9")
        self.clearbuttton.configure(highlightcolor="black")
        self.clearbuttton.configure(pady="0")
        self.clearbuttton.configure(text='''Clear''')

        self.backbutton = Button(self.Canvas1)
        self.backbutton.place(relx=0.71, rely=0.73, height=42, width=128)
        self.backbutton.configure(activebackground="#d9d9d9")
        self.backbutton.configure(activeforeground="#000000")
        self.backbutton.configure(background="#d9d9d9")
        self.backbutton.configure(command=studentloginportal12_support.backfunction)
        self.backbutton.configure(disabledforeground="#a3a3a3")
        self.backbutton.configure(foreground="#000000")
        self.backbutton.configure(highlightbackground="#d9d9d9")
        self.backbutton.configure(highlightcolor="black")
        self.backbutton.configure(pady="0")
        self.backbutton.configure(text='''Back''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.2, rely=0.07, height=31, width=447)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''LOGIN PORTAL''')






if __name__ == '__main__':
    vp_start_gui()



