#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 07:13:48 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global edib
    edib = StringVar()

def ebackfunction():
    print('deletebook6_support.ebackfunction')
    sys.stdout.flush()

def edeletefunction():
    print('deletebook6_support.edeletefunction')
    sys.stdout.flush()

def elogoutfunction():
    print('deletebook6_support.elogoutfunction')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import deletebook6
    deletebook6.vp_start_gui()


