#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 07:13:55 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import deletebook6_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    deletebook6_support.set_Tk_var()
    top = Delete_Block (root)
    deletebook6_support.init(root, top)
    root.mainloop()

w = None
def create_Delete_Block(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    deletebook6_support.set_Tk_var()
    top = Delete_Block (w)
    deletebook6_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Delete_Block():
    global w
    w.destroy()
    w = None


class Delete_Block:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "italic -underline 1 -overstrike 0"
        font9 = "-family {Segoe UI} -size 10 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("526x292+724+150")
        top.title("Delete Block")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.11, rely=0.24, relheight=0.56, relwidth=0.77)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=403)

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.07, rely=0.25, height=34, width=80)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''BID''')

        self.ebidentry = Entry(self.Canvas1)
        self.ebidentry.place(relx=0.35, rely=0.25,height=26, relwidth=0.61)
        self.ebidentry.configure(background="white")
        self.ebidentry.configure(disabledforeground="#a3a3a3")
        self.ebidentry.configure(font="TkFixedFont")
        self.ebidentry.configure(foreground="#000000")
        self.ebidentry.configure(highlightbackground="#d9d9d9")
        self.ebidentry.configure(highlightcolor="black")
        self.ebidentry.configure(insertbackground="black")
        self.ebidentry.configure(selectbackground="#c4c4c4")
        self.ebidentry.configure(selectforeground="black")
        self.ebidentry.configure(textvariable=deletebook6_support.edib)

        self.edeletebutton = Button(self.Canvas1)
        self.edeletebutton.place(relx=0.2, rely=0.67, height=42, width=98)
        self.edeletebutton.configure(activebackground="#d9d9d9")
        self.edeletebutton.configure(activeforeground="#000000")
        self.edeletebutton.configure(background="#d9d9d9")
        self.edeletebutton.configure(command=deletebook6_support.edeletefunction)
        self.edeletebutton.configure(disabledforeground="#a3a3a3")
        self.edeletebutton.configure(foreground="#000000")
        self.edeletebutton.configure(highlightbackground="#d9d9d9")
        self.edeletebutton.configure(highlightcolor="black")
        self.edeletebutton.configure(pady="0")
        self.edeletebutton.configure(text='''Delete''')

        self.ebackbutton = Button(self.Canvas1)
        self.ebackbutton.place(relx=0.6, rely=0.67, height=42, width=98)
        self.ebackbutton.configure(activebackground="#d9d9d9")
        self.ebackbutton.configure(activeforeground="#000000")
        self.ebackbutton.configure(background="#d9d9d9")
        self.ebackbutton.configure(command=deletebook6_support.ebackfunction)
        self.ebackbutton.configure(disabledforeground="#a3a3a3")
        self.ebackbutton.configure(foreground="#000000")
        self.ebackbutton.configure(highlightbackground="#d9d9d9")
        self.ebackbutton.configure(highlightcolor="black")
        self.ebackbutton.configure(pady="0")
        self.ebackbutton.configure(text='''Back''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.21, rely=0.07, height=31, width=267)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Delete Book''')

        self.elogoutbutton = Button(top)
        self.elogoutbutton.place(relx=0.86, rely=0.0, height=42, width=78)
        self.elogoutbutton.configure(activebackground="#d9d9d9")
        self.elogoutbutton.configure(activeforeground="#000000")
        self.elogoutbutton.configure(background="#d9d9d9")
        self.elogoutbutton.configure(command=deletebook6_support.elogoutfunction)
        self.elogoutbutton.configure(disabledforeground="#a3a3a3")
        self.elogoutbutton.configure(foreground="#000000")
        self.elogoutbutton.configure(highlightbackground="#d9d9d9")
        self.elogoutbutton.configure(highlightcolor="black")
        self.elogoutbutton.configure(pady="0")
        self.elogoutbutton.configure(text='''logout''')






if __name__ == '__main__':
    vp_start_gui()



